apiVersion: v2
name: msg-mono-all-local
description: Umbrella chart that includes all services (MySQL, Redis, Application, etc.)
type: application
version: 0.1.0

dependencies:
  - name: mysql
    version: 0.1.0
    repository: "file://../mysql"
    condition: mysql.enabled

# Note: Add more dependencies as services are added:
#  - name: redis
#    version: 0.1.0
#    repository: "file://../redis"
#    condition: redis.enabled
#  - name: application
#    version: 0.1.0
#    repository: "file://../application"
#    condition: application.enabled

