apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
  MYSQL_DATABASE: {{ .Values.mysql.database }}
  MYSQL_USER: {{ .Values.mysql.user }}
  MYSQL_PASSWORD: {{ .Values.mysql.password }}

